[package]
name = "z-gauges"
version = "0.1.0"
authors = ["Berkeley Martinez"]
edition = "2021"
build = "build.rs"

[dependencies]
slint = {version = "1.7.2"}

[build-dependencies]
slint-build = "1.7.2"


[features]
simulator = ["slint/renderer-winit-software", "slint/backend-winit"]

