import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 240px;
    height: 240px;
    in-out property <int> counter: 1;
    callback request-increase-value();

    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "+";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
